consumer_key: "75NB6SuRC2esZYH5AFB8Fymui"
consumer_secret: "Q8nPtUNBAESp1DypbwBcFc500s00jsx7IMjtgttaggfjv2xnmn"
access_key: "867445933486870529-iDa56aD5XLdn3LtqMNbMbza4r0mwn3W"
access_secret: "RV35h2HWTurx0KxWodoE9rNx8FCeHH60x2t67cx6B9n6Y"

twitter_users:
  - Catbread
  - bogmood
  - Rays_of_Hope
  - Kreepykitten
  - rockcryptid

num_epochs: 1
gen_epochs: 1
batch_size: 128
train_size: 1.0
model_name: "Satu_0_4"
weights_only: True
weights_path: "../models/model_0_3/Satu_0_3_weights.hdf5"
config_path: ""
vocab_path: ""
new_model: False

# Only applicable if new_model: True
model_config:
  rnn_layers: 2
  rnn_size: 128
  rnn_bidirectional: False
  max_length: 40
  dim_embeddings: 100
  word_level: False
